// src/components/Header.tsx
import { useState, useEffect, useRef } from 'react'
import { Link } from 'react-router-dom'
import './Header.css'

export default function Header() {
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const [isScrolled, setIsScrolled] = useState(false)
  const navRef = useRef<HTMLElement>(null)

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50)
    }

    const handleClickOutside = (e: MouseEvent) => {
      if (navRef.current && !navRef.current.contains(e.target as Node)) {
        setIsMenuOpen(false)
      }
    }

    window.addEventListener('scroll', handleScroll)
    document.addEventListener('click', handleClickOutside)

    return () => {
      window.removeEventListener('scroll', handleScroll)
      document.removeEventListener('click', handleClickOutside)
    }
  }, [])

  const closeMenu = () => setIsMenuOpen(false)

  return (
    <header className={`header ${isScrolled ? 'scrolled' : ''}`}>
      <nav className="nav" ref={navRef}>
        <Link to="/" className="logo" onClick={closeMenu}>MiPortafolio</Link>

        <button className="menu-toggle" onClick={() => setIsMenuOpen(!isMenuOpen)}>
          ☰
        </button>

        <ul className={`nav-links ${isMenuOpen ? 'active' : ''}`}>
          <li><Link to="/" onClick={closeMenu}>Home</Link></li>
          <li><Link to="/about" onClick={closeMenu}>About</Link></li>
          <li><Link to="/certifications" onClick={closeMenu}>Certificaciones</Link></li>
          <li><Link to="/projects" onClick={closeMenu}>Proyectos</Link></li>
          <li><Link to="/contact" onClick={closeMenu}>Contacto</Link></li>
        </ul>
      </nav>
    </header>
  )
}

// src/app/componets/header/header.component.ts
import { Component, ElementRef, HostListener } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  isMenuOpen = false;
  isScrolled = false;

  constructor(private eRef: ElementRef) {}

  toggleMenu() {
    this.isMenuOpen = !this.isMenuOpen;
  }

  closeMenu() {
    this.isMenuOpen = false;
  }

  @HostListener('window:scroll', [])
  onWindowScroll() {
    this.isScrolled = window.scrollY > 50;
  }

  // Detectar click fuera del menú en móvil
  @HostListener('document:click', ['$event'])
  onClickOutside(event: Event) {
    const target = event.target as HTMLElement;
    const clickedInside = this.eRef.nativeElement.contains(target);

    if (!clickedInside && this.isMenuOpen) {
      this.isMenuOpen = false;
    }
  }
}

<header class="header" [class.scrolled]="isScrolled">
  <nav class="nav">
    <!-- Logo -->
    <a routerLink="/" class="logo" (click)="closeMenu()">MiPortafolio</a>

    <!-- Botón menú (solo móvil) -->
    <button class="menu-toggle" (click)="toggleMenu()">
      ☰
    </button>

    <!-- Links -->
    <ul class="nav-links" [class.active]="isMenuOpen">
      <li><a routerLink="/" (click)="closeMenu()">Home</a></li>
      <li><a routerLink="/About" (click)="closeMenu()">About</a></li>
      <li><a routerLink="/certifiaciones" (click)="closeMenu()">Certificaciones</a></li>
      <li><a routerLink="/projects" (click)="closeMenu()">Proyectos</a></li>
      <li><a routerLink="/contacto" (click)="closeMenu()">Contacto</a></li>
    </ul>
  </nav>
</header>
