// src/pages/Home.tsx
import { useEffect, useRef } from 'react'
import { Link } from 'react-router-dom'
import './Home.css'

export default function Home() {
  const heroRef = useRef<HTMLDivElement>(null)
  const secondRef = useRef<HTMLDivElement>(null)
  const thirdRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    // fadeInUp for hero
    if (heroRef.current) {
      heroRef.current.style.opacity = '0'
      heroRef.current.style.transform = 'translateY(40px)'
      requestAnimationFrame(() => {
        if (heroRef.current) {
          heroRef.current.style.transition = 'opacity 0.8s ease-out, transform 0.8s ease-out'
          heroRef.current.style.opacity = '1'
          heroRef.current.style.transform = 'translateY(0)'
        }
      })
    }

    // fadeIn for second section
    if (secondRef.current) {
      secondRef.current.style.opacity = '0'
      requestAnimationFrame(() => {
        if (secondRef.current) {
          secondRef.current.style.transition = 'opacity 1.2s ease-in'
          secondRef.current.style.opacity = '1'
        }
      })
    }

    // stagger for cards
    if (thirdRef.current) {
      const items = thirdRef.current.querySelectorAll('li')
      items.forEach((item, i) => {
        const el = item as HTMLElement
        el.style.opacity = '0'
        el.style.transform = 'translateY(20px)'
        requestAnimationFrame(() => {
          el.style.transition = `opacity 0.6s ease-out ${i * 0.2}s, transform 0.6s ease-out ${i * 0.2}s`
          el.style.opacity = '1'
          el.style.transform = 'translateY(0)'
        })
      })
    }
  }, [])

  return (
    <main>
      <div className="hero-section" ref={heroRef}>
        <h1>Ingeniero en Software. Fullstack Developer<br /> y Más</h1>
      </div>

      <div className="segunda-seccion" ref={secondRef}>
        <p>
          Hola, soy David! <br />
          Soy desarrollador de software y me encanta construir cosas útiles con
          código. Me gusta la fotografia y la música. Me gustan los retos, aprender
          cosas nuevas y hacer que las ideas se vuelvan realidad.
        </p>
        <Link to="/about">Más sobre mí:</Link>
      </div>

      <div className="tercera-seccion" ref={thirdRef}>
        <ul className="tarjetas-navegacion">
          <li>
            <Link to="/certifications">Certificaciones</Link>
          </li>
          <li>
            <Link to="/projects">Proyectos</Link>
          </li>
          <li>
            <Link to="/contact">Contacto</Link>
          </li>
        </ul>
      </div>
    </main>
  )
}

// src/app/pages/home/home.component.ts
import { Component } from '@angular/core';
import {
  trigger,
  state,
  style,
  transition,
  animate,
  query,
  stagger,
} from '@angular/animations';
import { ScrollAnimateDirective } from '../shared/directives/scroll-animate.directive';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  imports: [ScrollAnimateDirective],
  styleUrls: ['./home.component.css'],
  animations: [
    // Animación para el título
    trigger('fadeInUp', [
      transition(':enter', [
        style({ opacity: 0, transform: 'translateY(40px)' }),
        animate('800ms ease-out', style({ opacity: 1, transform: 'translateY(0)' }))
      ])
    ]),

    // Animación para el párrafo y enlace
    trigger('fadeIn', [
      transition(':enter', [
        style({ opacity: 0 }),
        animate('1200ms ease-in', style({ opacity: 1 }))
      ])
    ]),

    // Animación con retardo entre elementos (tarjetas)
    trigger('staggerFadeIn', [
      transition(':enter', [
        query('li', [
          style({ opacity: 0, transform: 'translateY(20px)' }),
          stagger(200, [
            animate('600ms ease-out', style({ opacity: 1, transform: 'translateY(0)' }))
          ])
        ])
      ])
    ])
  ]
})
export class HomeComponent {}

<main>
  <div class="hero-section" [@fadeInUp]>
    <h1>Ingeniero en Software. Fullstack Developer<br> y Más</h1>
  </div>

  <div class="segunda-seccion" [@fadeIn]>
    <p>
      Hola, soy David! <br />
      Soy desarrollador de software y me encanta construir cosas útiles con
      código. Me gusta la fotografia y la música. Me gustan los retos, aprender
      cosas nuevas y hacer que las ideas se vuelvan realidad.
    </p>
    <a href="/About">Más sobre mí:</a>
  </div>

  <div  class="tercera-seccion" [@staggerFadeIn]>
    <ul  class="tarjetas-navegacion">
      <li >
        <a href="/certifiaciones">Certificaciones</a>
      </li>
      <li><a href="/projects">Proyectos</a></li>
      <li>
        <a href="/contacto">Contacto</a>
      </li>
    </ul>
  </div>
</main>
